services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - ./src:/src

  spark-master:
    image: video-upscaling-image:v2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./src/spark:/opt/spark/app

  spark-worker:
    image: video-upscaling-image:v2
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"
    volumes:
      - ./src/spark:/opt/spark/app

  producer:
    build:
      context: ./src/producer  # This is the directory containing the Dockerfile
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      FRAME_DIR: /frames
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: webcam-frames
    volumes:
      - ./src:/app
      - ./frames:/frames
    command: python /app/producer/producer.py
